version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: szamitastudomany-vizsga
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.szamitastudomany.rule=Host(`szamitastudomany.prstart.hu`)"
      - "traefik.http.routers.szamitastudomany.entrypoints=websecure"
      - "traefik.http.routers.szamitastudomany.tls.certresolver=myresolver"
    networks:
      - traefik

networks:
  traefik:
    external: true